# Site settings
title: Zeka Solutions
description: >- # this means to ignore newlines until "baseurl:"
  This is Ethereal, my latest, greatest, and quite possibly most unique template for HTML5 UP.
  Since releasing Parallelism 3-4 years ago (!!!), I've been dying to do another side-scrolling
  template with more in the way of flexibility/customization potential. The result is this template,
  Ethereal, which combines a robust side-scrolling framework of my own creation (with various
  "scroll-assist" features like drag/momentum scrolling, keyboard shortcuts, etc.) with a unique
  look and feel, a lightbox gallery, tons of customization options, and, of course, full
  responsiveness. Hope you dig it :)

# Contact information
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555
email: youremailaddress@gmail.com

# Social settings
facebook_url: https://github.com/apehex
instagram_url: https://github.com/apehex
linkedin_url: https://github.com/apehex
pinterest_url: https://github.com/apehex
twitter_url: https://github.com/apehex

# Optional elements
logo: /assets/images/logo.png
favicon: /assets/images/favicon.ico
legal_terms:
  url: /en/legal-terms/
privacy_policy:
  url: /en/privacy-policy/
  third_party:
    hosting: github


# Recaptcha in forms
recaptcha:
  sitekey: 6LeidzMpAAAAAL6PtpDM2H4eOK81d_OFoXDBRra2

# Collections
collections:
  articles:
    output: false
  redirects:
    output: true
    permalink: /:path/

# Default settings
defaults:
  -
    scope:
      type: "redirects"
    values:
      layout: "redirect"
      lang: "x-default"
  -
    scope:
      path: ""
    values:
      menu: default
  -
    scope:
      path: "en"
    values:
      lang: "en"
  -
    scope:
      path: "sq"
    values:
      lang: "sq"

# Build settings
permalink: pretty
markdown: kramdown
sass:
  sourcemap: never
  style: compressed
plugins:
  - jekyll-seo-tag
theme: jekyll-theme-twenty

# Publication settings
baseurl: "zeka-trade" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
author: vlere